-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 11, 2019 at 02:33 PM
-- Server version: 10.1.31-MariaDB
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `clnews`
--
CREATE DATABASE IF NOT EXISTS `clnews` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `clnews`;

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `category` varchar(10) NOT NULL,
  `tags` longtext NOT NULL,
  `source` varchar(100) NOT NULL,
  `text` longtext NOT NULL,
  `image` varchar(100) NOT NULL,
  `writer` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`id`, `title`, `category`, `tags`, `source`, `text`, `image`, `writer`) VALUES
(1, 'MotoGP Australia 2018, Marc Marquez Menggila, Raih Pole Position, Rossi dan Dovizioso Melempem.', 'MOTOGP', '#marcmarquezpolepositionMotoGPAustralia2018 #poleposition #MotoGPAustralia2018 #MarcMarquez #ValentiRossi #AndreaDovisiozo', 'Sumber Kompas.com', 'Juara dunia Marc Marquez berhasil mencatatkan diri sebagai pebalap tercepat di sesi kualifikasi Sabtu (27/10/2018). Ini membuatnya memulai balapan di GP Australia dari posisi terdepan. Padahal beberapa kali Marquez terjatuh.<br>\r\nBahkan pada Free Practice 3, Marquez terjatuh saat melibas tikungan ke-4 di sirkuit Phillip Island. Beruntung Marc Marquez enggak cedera sedikit pun. Sang juara dunia ini berhasil mencatatkan waktu 1 menit 29.714 detik dan merupakan yang tercepat di FP 3. Sebelumnya di FP1, pembalap ini sempat terperosok di gravel dan tercecer di belakang.<br>\r\nKebangkitan dan penampilan luar biasa Marc Marquez itu disebut-sebut karena faktor sudah bertemu dengan legenda MotoGP yang rekor juara dunianya berhasil disamai. Legenda MotoGP itu tak bukan adalah Michael Doohan. Disebut-sebut, Marc Marquez minta diupayakan bisa bertatap muka langsung dengan Michael Doohan.<br>', 'assets/img/news/dGL5hwyoft1445085700.jpg', 'Andra'),
(2, 'Formula 1: Mengenal Sosok Charles Leclerc, Pembalap Baru Ferrari', 'FORMULA-1', '#formula1 #ferrari #charlesleclerc #f1', 'sporttempo.com', 'Charles Leclerc mencuri perhatian publik ketika pada September lalu Ferrari mengonfirmasi bahwa pembalap asal Monaco itu akan menjadi rekan Sebastian Vettel untuk balapan Formula 1 musim 2019. Di usia yang baru menginjak 21 tahun, Leclerc akan menjadi pebalap termuda tim Kuda Jingkrak menggantikan Kimi Raikkonen yang bertukar kursi dengannya di Sauber.<br>Lalu apa yang membuat tim yang bermarkas di Maranello, Italia itu terpikat kepada si pembalap muda itu? Finis di peringkat 13 dengan 39 poin bersama Sauber, Leclerc keluar sebagai pembalap rookie terbaik dalam debutnya di Formula 1 tahun lalu.<br>Membalap untuk Ferrari adalah salah satu kursi paling mahal juga sangat berat mengingat siapapun yang duduk di bangku mobil Ferrari akan mendapati tekanan yang besar karena bekerja dengan nama-nama besar, dalam kesempatan ini adalah sang juara dunia empat kali Sebastian Vettel.<br>\"Dia telah membalap dengan apa yang dia punyai sejauh ini, dia telah menggunakan kesempatan yang dia miliki, mencetak poin dengan mobil yang sulit untuk mencetak poin,\" kata Sebastian Vettel soal performa Leclerc bersama Sauber.<br>Performa Leclerc pun menuai pujian dari pebalap Mercedes Lewis Hamilton yang mengatakan bahwa Leclerc \"benar-benar memiliki potensi untuk melakukan hal hebat (di Formula 1), dan anda belum tentu bisa mengatakan hal itu kepada setiap pembalap muda yang telah datang di tahun-tahun yang telah berlalu,\" kata Hamilton.<br>Vettel dan Hamilton melihat Leclerc adalah salah satu pembalap yang tidak boleh diremehkan, dan jarang-jarang kedua juara dunia itu menyepakati satu hal yang sama.<br>GP Monaco di halaman belakang rumah Lahir di Monaco, Leclerc sejak kecil sudah dikenalkan oleh keluarganya dengan dunia balapan Formula 1.<br>\"Seingatku waktu itu aku berumur empat tahun. Aku dan keluarga menghabiskan siang dengan teman-teman ketika Grand Prix Monaco. Kami duduk di teras rumah mereka, yang terletak di atas exit tikungan pertama, Sainte Devote,\" ingat Leclerc di laman resmi Sauber F1.<br>Leclerc kecil dan kawan-kawan sepermainannya bermain mobil-mobilan dan mendengar bisingnya suara mesin mobil F1 kala itu.<br>\"Kalian pasti punya kenangan masa kecil, yang tertanam sangat dalam di memori kalian. Ini adalah salah satu memori pertamaku dan yang paling jelas,\" kata Leclerc.<br>Di umur itu pula Leclerc pertama kali menjajal mobil karting ketika diajak ayahnya bermain ke sirkuit milik temannya, Phillippe Bianchi, ayah dari mendiang pebalap F1 Jules Bianchi, yang meninggal pada 2015.', 'assets/img/news/800303_720.jpg', 'Andra'),
(3, 'Direktur motorsport Formula 1, Ross Brawn, menilai kompetisi olahraga jet darat tersebut tidak ramah', 'FORMULA-1', '#rossbrawn #mclaren #williams #formula 1 #f1', 'gpfans.com', 'Direktur motorsport Formula 1, Ross Brawn, menilai kompetisi olahraga jet darat tersebut tidak ramah terhadap tim-tim tua seperti McLaren dan Williams.<br>McLaren dan William adalah dua dari tiga tim yang terbanyak meraih gelar juara konstruktor.<br>Namun, semua kemenangan mereka terjadi lebih dari dua dekade lalu. Sejak saat itu, kiprah mereka seperti tenggelam oleh tim-tim seperti Mercedes dan Red Bull.<br>Ross Brawn menilai bahwa kesulitan yang dialami McLaren dan Williams adalah bukti bahwa olahraga bisa tidak mengenal ampun.<br>\"McLaren dan Williams adalah tim dengan sejarah hebat. Sayangnya, Formula 1 bukan olahraga yang sanggup menghormati sejarah. F1 hanya menghormati momen yang sedang berlangsung,\" kata Brawn, dikutip BolaSport.com dari gpfans.com.<br>Brawn pun berharap McLaren dan Williams bangkit, tetapi mengakui bahwa F1 adalah cabang olahraga yang kompetitif.<br>\"Kami di Formula 1 sangat ingin tim-tim lama bisa kembali kompetitif, karena mereka adalah tim hebat. Namun, Formula 1 tak kenal ampun. Kalau Anda tidak melakukan pekerjaan dengan baik, hasilnya akan terlihat pada balapan. McLaren dan Williams mungkin bisa bangkit, namun sulit,\" tuturnya melanjutkan.\r\n\r\n', 'assets/img/news/medium_3df0afc69bf0ecc326bd90d5918ff229.jpg', 'Andra'),
(4, 'Cara Ini Dinilai Bikin Formula 1 Lebih Seru dengan Salip-menyalip', 'FORMULA-1', '#formula1', 'kompas.com', 'Bos tim Toro Rosso, Franz Tost, menilai balapan Formula 1 akan lebih seru dengan adanya pengurangan \"downforce\" pada mobil balap jet darat. Downforce adalah bagian dari aspek aerodinamis yang memungkinkan mobil F1 melaju lebih cepat. Pada musim balap 2017, F1 menerapkan downforce yang lebih tinggi. Dikutip dari Motorsport, downforce yang lebih tinggi membuat mobil melaju lebih cepat di tikungan.<br>Namun, Tost menilai hal tersebut membuat para pembalap kesulitan melakukan aksi salip menyalip.<br>\"Kami memiliki begitu banyak downforce, yang berarti, di tikungan berkecepatan tinggi, tidak ada yang bisa menempel mobil di depannya karena ada udara kotor. Titik pengereman pun juga tidak ada,\" kata Tost kepada Motorsport.com, Rabu (9/1/2019). \"Jadi bagaimana Anda bisa menyalip?\" lanjutnya.<br>Tost menilai usulannya itu pasti akan bisa diterima orang-orang berpengalaman di Federasi Balap Mobil Dunia (FIM) dan Manajemen Formula 1 (FOM) seperti Ross Brawn dan Pat Symonds. Namun, ia menyadari usulan itu akan ditentang tim-tim lain, terutama para teknisi mesin. \"Menurut saya, minimal harus dikurangi 40-50 persen dari downforce sekarang, sehingga mobil lebih goyah di tikungan,\" ujar Tost. \"Dengan begitu, kita akan melihat pebalap harus berjibaku dengan mobil mereka. Mobil akan jauh lebih kencang di trek lurus. Anda bisa dapat peluang untuk menyalip. Anda juga bisa menempel mobil di depan saat melewati tikungan,\" ucap Tost menambahkan.\r\n', 'assets/img/news/100565204.jpg', 'Andra'),
(5, 'Menurut bos tim Toro Rosso, Franz Tost, pengurangan downforce sebesar 40-50 persen dapat membuat bal', 'FORMULA-1', '#beritaf1', 'id.motosport.com', 'Tahun ini, mobil-mobil Formula 1 bakal mengalami sejumlah perubahan kecil, termasuk desain sayap depan dan bargeboard yang lebih sederhana. Hal ini bertujuan untuk mengurangi sensitivitas mobil terhadap udara kotor sehingga balapan bisa berjalan lebih ketat.<br>Pada 2017, F1 memperkenalkan mobil generasi terbaru dengan downforce yang lebih tinggi untuk menghasilkan mobil tercepat sepanjang sejarah grand prix. Namun, menurut Tost, hal ini membuat para pembalap kesulitan melakukan aksi menyalip.<br>\"Kami memiliki begitu banyak downforce, yang berarti, di tikungan berkecepatan tinggi, tidak ada yang bisa menempel mobil di depannya karena ada udara kotor. Titik pengereman pun juga tidak ada,\" kata Tost kepada Motorsport.com. \"Jadi bagaimana Anda bisa menyalip?.<br>\"Ini berarti, FIA, FOM â€“ mereka diisi orang berpengalaman di sana seperti Ross Brawn dan Pat Symonds â€“ jadi mereka tahu apa yang seharusnya dilakukan: Kurangi ketergantungan aero, dimulai dengan downforce.<br>\"Menurut saya, minimal harus dikurangi 40-50 persen dari jumlah downforce sekarang, sehingga mobil lebih goyah di tikungan.<br>\"Dengan begitu, kita akan melihat pembalap harus berjibaku dengan mobil mereka.<br>\"Mobil akan jauh lebih kencang di trek lurus, jadi Anda bisa dapat peluang untuk menyalip. Anda juga bisa menempel mobil di depan saat melewati tikungan.<br>\"Perubahan ini sebenarnya mudah untuk diwujudkan, tinggal apakah mereka mau atau tidak?\".<br>Akan tetapi, Tost menyadari idenya bakal mendapat pertentangan dari tim-tim lain. Ketika ditanya siapa yang menentang proposalnya, ia menjawab: \"Tim-tim [lain]. Jangan pernah tanya mereka.<br>\"[Pembuat regulasi] seharusnya membuat regulasi dan langsung katakan \'terima atau tidak\'. Tapi mereka masih menanyakan hal seperti itu kepada tim. Mereka mendatangi Grup Kerja Teknis, dan Anda tahu siapa yang ada di sana? Para teknisi. Jadi jangan pernah bertanya ke teknisi!\" tukasnya.\r\n\r\n', 'assets/img/news/kimi-raikkonen-ferrari-sf71h--1.jpg', 'Andra'),
(6, 'Kepindahan Raikkonen jadi pukulan bagi F1', 'FORMULA-1', '#beritaf1 #kimiraikkonen', 'id.motosport.com', 'Setelah lima tahun membalap bersama Ferrari, Raikkonen hijrah ke Sauber untuk musim 2019, sekaligus bereuni dengan tim tempat ia melakukan debut F1 pada 2001.<br>Kepindahan pembalap asal Finlandia itu dipicu oleh keputusan Ferrari mempromosikan Charles Leclerc sebagai pendamping baru Sebastian Vettel tahun depan.<br>Padahal Raikkonen tampil cukup apik sepanjang 2018, menyabet posisi pole di Italia serta merebut kemenangan di Amerika Serikat. Selain itu sosok The Iceman masih menjadi idola banyak penggemar.<br>Oleh sebab itu Wolff berpikir bahwa kepindahan Raikkonen dari Ferrari akan membawa dampak negatif pada Formula 1.<br>â€œKimi sudah tidak lagi di Ferrari, tim yang punya kemampuan untuk memenangi balapan. Menurut saya ini akan berdampak besar pada F1,â€ kata Wolff dalam sebuah sesi wawancara yang dihadiri Motorsport.com.<br>â€œDia punya karakter yang luar biasa. Di zaman sekarang, yang penuh dengan ego dan ditambah ramainya media sosial, dia tetap menjadi dirinya sendiri. Dia salah satu dari sedikit orang yang masih bisa seperti itu.<br>â€œDia punya nilai-nilai sendiri, dan ia setia dengan itu. Jadi dia adalah orang yang otentik. Itu yang dicintai para fans. Jadi, ketika Kimi sudah tidak lagi di Ferrari, itu menjadi pukulan untuk kita semua.<br>â€œTapi setidaknya dia tidak pensiun. Dia sekarang di Sauber. Namun, tetap saja ini cukup disayangkan karena Alonso sudah tidak lagi di F1, dan kita kehilangan dua pembalap dengan kepribadian yang luar biasa. Kimi dan Ferrari adalah kombinasi yang begitu menarik.â€<br>Meski Sauber satu tingkat di bawah Ferrari, Wolff yakin sang juara dunia 2007 itu telah membuat keputusan yang tepat dengan bertahan di F1.', 'assets/img/news/kimi-raikkonen-ferrari-in-par-.jpg', 'Andra'),
(7, 'Redding: Valentino Rossi Tak Senekat Marquez di MotoGP', 'MOTOGP', '#scottredding #valentinorossi #marcmarquez #motogp #motogp2019\r\n', 'cnnindonesia.com', 'Juara dunia Marc Marquez berhasil mencatatkan diri sebagai pebalap tercepat di sesi kualifikasi Sabtu (27/10/2018). Ini membuatnya memulai balapan di GP Australia dari posisi terdepan. Padahal beberapa kali Marquez terjatuh.<br>\r\nBahkan pada Free Practice 3, Marquez terjatuh saat melibas tikungan ke-4 di sirkuit Phillip Island. Beruntung Marc Marquez enggak cedera sedikit pun. Sang juara dunia ini berhasil mencatatkan waktu 1 menit 29.714 detik dan merupakan yang tercepat di FP 3. Sebelumnya di FP1, pembalap ini sempat terperosok di gravel dan tercecer di belakang.<br>\r\nKebangkitan dan penampilan luar biasa Marc Marquez itu disebut-sebut karena faktor sudah bertemu dengan legenda MotoGP yang rekor juara dunianya berhasil disamai. Legenda MotoGP itu tak bukan adalah Michael Doohan. Disebut-sebut, Marc Marquez minta diupayakan bisa bertatap muka langsung dengan Michael Doohan.<br>', 'assets/img/news/c4ae1df3-cbfc-4c13-b4df-bcc2a681297c_169.jpeg', 'Andra'),
(8, 'Cerita Aktivitas Para Pembalap Menyongsong Balap MotoGP 2019', 'MOTOGP', '#marcmarquezpolepositionMotoGPAustralia2018 #poleposition #MotoGPAustralia2018 #MarcMarquez #ValentiRossi #AndreaDovisiozo', 'Sumber Kompas.com', 'Juara dunia Marc Marquez berhasil mencatatkan diri sebagai pebalap tercepat di sesi kualifikasi Sabtu (27/10/2018). Ini membuatnya memulai balapan di GP Australia dari posisi terdepan. Padahal beberapa kali Marquez terjatuh.<br>\r\nBahkan pada Free Practice 3, Marquez terjatuh saat melibas tikungan ke-4 di sirkuit Phillip Island. Beruntung Marc Marquez enggak cedera sedikit pun. Sang juara dunia ini berhasil mencatatkan waktu 1 menit 29.714 detik dan merupakan yang tercepat di FP 3. Sebelumnya di FP1, pembalap ini sempat terperosok di gravel dan tercecer di belakang.<br>\r\nKebangkitan dan penampilan luar biasa Marc Marquez itu disebut-sebut karena faktor sudah bertemu dengan legenda MotoGP yang rekor juara dunianya berhasil disamai. Legenda MotoGP itu tak bukan adalah Michael Doohan. Disebut-sebut, Marc Marquez minta diupayakan bisa bertatap muka langsung dengan Michael Doohan.<br>', 'assets/img/news/Marquez-Phillip-Island-MotoGP-2017.jpg', 'Andra'),
(9, '3 Pembalap MotoGP yang Ikutan 10 Years Challenge, Ada Duo Repsol Honda', 'MOTOGP', '#marcmarquezpolepositionMotoGPAustralia2018 #poleposition #MotoGPAustralia2018 #MarcMarquez #ValentiRossi #AndreaDovisiozo', 'Sumber Kompas.com', 'Juara dunia Marc Marquez berhasil mencatatkan diri sebagai pebalap tercepat di sesi kualifikasi Sabtu (27/10/2018). Ini membuatnya memulai balapan di GP Australia dari posisi terdepan. Padahal beberapa kali Marquez terjatuh.<br>\r\nBahkan pada Free Practice 3, Marquez terjatuh saat melibas tikungan ke-4 di sirkuit Phillip Island. Beruntung Marc Marquez enggak cedera sedikit pun. Sang juara dunia ini berhasil mencatatkan waktu 1 menit 29.714 detik dan merupakan yang tercepat di FP 3. Sebelumnya di FP1, pembalap ini sempat terperosok di gravel dan tercecer di belakang.<br>\r\nKebangkitan dan penampilan luar biasa Marc Marquez itu disebut-sebut karena faktor sudah bertemu dengan legenda MotoGP yang rekor juara dunianya berhasil disamai. Legenda MotoGP itu tak bukan adalah Michael Doohan. Disebut-sebut, Marc Marquez minta diupayakan bisa bertatap muka langsung dengan Michael Doohan.<br>', 'assets/img/news/3-pembalap-motogp-yang-ikutan-10-years-challenge-ada-duo-repsol-honda-foSfpmAccw.jpg', 'Andra'),
(10, 'Vinales Harus Mulai Kalahkan Rossi di Tiap Balapan pada MotoGP 2019', 'MOTOGP', '#marcmarquezpolepositionMotoGPAustralia2018 #poleposition #MotoGPAustralia2018 #MarcMarquez #ValentiRossi #AndreaDovisiozo', 'Sumber Kompas.com', 'Juara dunia Marc Marquez berhasil mencatatkan diri sebagai pebalap tercepat di sesi kualifikasi Sabtu (27/10/2018). Ini membuatnya memulai balapan di GP Australia dari posisi terdepan. Padahal beberapa kali Marquez terjatuh.<br>\r\nBahkan pada Free Practice 3, Marquez terjatuh saat melibas tikungan ke-4 di sirkuit Phillip Island. Beruntung Marc Marquez enggak cedera sedikit pun. Sang juara dunia ini berhasil mencatatkan waktu 1 menit 29.714 detik dan merupakan yang tercepat di FP 3. Sebelumnya di FP1, pembalap ini sempat terperosok di gravel dan tercecer di belakang.<br>\r\nKebangkitan dan penampilan luar biasa Marc Marquez itu disebut-sebut karena faktor sudah bertemu dengan legenda MotoGP yang rekor juara dunianya berhasil disamai. Legenda MotoGP itu tak bukan adalah Michael Doohan. Disebut-sebut, Marc Marquez minta diupayakan bisa bertatap muka langsung dengan Michael Doohan.<br>', 'assets/img/news/093087900_1543635545-Rossi_dan_Vinales.jpg', 'Andra'),
(11, 'Rekrutan Anyar PSM Makassar Ternyata Kakak Kandung dari Bintang Muda NBA', 'NBA', '#psmmakassar #nba #chicagobulls #eeromarkkanen #LauriMarkkanen', 'bolasport.com', 'Nama Eero Markkanen resmi diumumkan sebagai pemain anyar PSM Makassar pada Senin (14/1/2019).<br>Pemain asal Finlandia ini memiliki reputasi yang cukup baik karena pernah memperkuat tim Real Madrid B pada musim 2014-2015.<br>Berposisi sebagai striker, Eero Markkanen bakal diplot menjadi juru gedor PSM Makassar pada musim mendatang.<br>Postur tinggi yang dimiliki penyerang 27 tahun itu, 197 cm (menurut Soccerway, red) tentu bakal menguntungkannya dalam menghadapi duel bola atas.<br>\r\n\r\nTubuh jangkung Eero Markkanen tersebut rupanya tak lepas dari faktor genetik yang dimiliki oleh keluarganya.<br>Bahkan, ayah dan adik kandungnya memiliki postur tubuh yang lebih tinggi dibandingkan pemilik anyar nomor punggung 9 di PSM Makassar itu.<br>Sebagai informasi BolaSporter, ayah dari Eero Markkanen, Pekka Markkanen, memiliki tinggi 208 cm. Sedangkan sang adik, Lauri Markkanen, lebih menjulang dengan 213 cm.', 'assets/img/news/medium_47c4d91335e759dc34f6c140b872100d.jpg', 'Andra'),
(12, 'Pemerintah Turki Terus Buru Pemain NBA', 'NBA', '#psmmakassar #nba #chicagobulls #eeromarkkanen #LauriMarkkanen', 'kompas.com', 'Nama Eero Markkanen resmi diumumkan sebagai pemain anyar PSM Makassar pada Senin (14/1/2019).<br>Pemain asal Finlandia ini memiliki reputasi yang cukup baik karena pernah memperkuat tim Real Madrid B pada musim 2014-2015.<br>Berposisi sebagai striker, Eero Markkanen bakal diplot menjadi juru gedor PSM Makassar pada musim mendatang.<br>Postur tinggi yang dimiliki penyerang 27 tahun itu, 197 cm (menurut Soccerway, red) tentu bakal menguntungkannya dalam menghadapi duel bola atas.<br>\r\n\r\nTubuh jangkung Eero Markkanen tersebut rupanya tak lepas dari faktor genetik yang dimiliki oleh keluarganya.<br>Bahkan, ayah dan adik kandungnya memiliki postur tubuh yang lebih tinggi dibandingkan pemilik anyar nomor punggung 9 di PSM Makassar itu.<br>Sebagai informasi BolaSporter, ayah dari Eero Markkanen, Pekka Markkanen, memiliki tinggi 208 cm. Sedangkan sang adik, Lauri Markkanen, lebih menjulang dengan 213 cm.', 'assets/img/news/1668190817.jpg', 'Andra'),
(13, 'Hasil NBA: Cavs Menang di Kandang Lakers', 'NBA', '#psmmakassar #nba #chicagobulls #eeromarkkanen #LauriMarkkanen', 'sport.detik.com', 'Nama Eero Markkanen resmi diumumkan sebagai pemain anyar PSM Makassar pada Senin (14/1/2019).<br>Pemain asal Finlandia ini memiliki reputasi yang cukup baik karena pernah memperkuat tim Real Madrid B pada musim 2014-2015.<br>Berposisi sebagai striker, Eero Markkanen bakal diplot menjadi juru gedor PSM Makassar pada musim mendatang.<br>Postur tinggi yang dimiliki penyerang 27 tahun itu, 197 cm (menurut Soccerway, red) tentu bakal menguntungkannya dalam menghadapi duel bola atas.<br>\r\n\r\nTubuh jangkung Eero Markkanen tersebut rupanya tak lepas dari faktor genetik yang dimiliki oleh keluarganya.<br>Bahkan, ayah dan adik kandungnya memiliki postur tubuh yang lebih tinggi dibandingkan pemilik anyar nomor punggung 9 di PSM Makassar itu.<br>Sebagai informasi BolaSporter, ayah dari Eero Markkanen, Pekka Markkanen, memiliki tinggi 208 cm. Sedangkan sang adik, Lauri Markkanen, lebih menjulang dengan 213 cm.', 'assets/img/news/usatsi_11711025.jpg', 'Andra'),
(14, 'Turki incar pemain basket NBA yang sebut Erdogan \'diktator\'', 'NBA', '#psmmakassar #nba #chicagobulls #eeromarkkanen #LauriMarkkanen', 'bolasport.com', 'Nama Eero Markkanen resmi diumumkan sebagai pemain anyar PSM Makassar pada Senin (14/1/2019).<br>Pemain asal Finlandia ini memiliki reputasi yang cukup baik karena pernah memperkuat tim Real Madrid B pada musim 2014-2015.<br>Berposisi sebagai striker, Eero Markkanen bakal diplot menjadi juru gedor PSM Makassar pada musim mendatang.<br>Postur tinggi yang dimiliki penyerang 27 tahun itu, 197 cm (menurut Soccerway, red) tentu bakal menguntungkannya dalam menghadapi duel bola atas.<br>\r\n\r\nTubuh jangkung Eero Markkanen tersebut rupanya tak lepas dari faktor genetik yang dimiliki oleh keluarganya.<br>Bahkan, ayah dan adik kandungnya memiliki postur tubuh yang lebih tinggi dibandingkan pemilik anyar nomor punggung 9 di PSM Makassar itu.<br>Sebagai informasi BolaSporter, ayah dari Eero Markkanen, Pekka Markkanen, memiliki tinggi 208 cm. Sedangkan sang adik, Lauri Markkanen, lebih menjulang dengan 213 cm.', 'assets/img/news/_105212418_85ed4796-be02-4db5-8a72-bac9a2dd0a74.jpg', 'Andra'),
(15, 'NBA: Irving Dominan, Celtics Raih Kemenangan Krusial atas Raptors', 'NBA', '#psmmakassar #nba #chicagobulls #eeromarkkanen #LauriMarkkanen', 'bolasport.com', 'Nama Eero Markkanen resmi diumumkan sebagai pemain anyar PSM Makassar pada Senin (14/1/2019).<br>Pemain asal Finlandia ini memiliki reputasi yang cukup baik karena pernah memperkuat tim Real Madrid B pada musim 2014-2015.<br>Berposisi sebagai striker, Eero Markkanen bakal diplot menjadi juru gedor PSM Makassar pada musim mendatang.<br>Postur tinggi yang dimiliki penyerang 27 tahun itu, 197 cm (menurut Soccerway, red) tentu bakal menguntungkannya dalam menghadapi duel bola atas.<br>\r\n\r\nTubuh jangkung Eero Markkanen tersebut rupanya tak lepas dari faktor genetik yang dimiliki oleh keluarganya.<br>Bahkan, ayah dan adik kandungnya memiliki postur tubuh yang lebih tinggi dibandingkan pemilik anyar nomor punggung 9 di PSM Makassar itu.<br>Sebagai informasi BolaSporter, ayah dari Eero Markkanen, Pekka Markkanen, memiliki tinggi 208 cm. Sedangkan sang adik, Lauri Markkanen, lebih menjulang dengan 213 cm.', 'assets/img/news/053011700_1542426911-AP18321118834476.jpg', 'Andra'),
(16, 'Eks Arsenal: Masalah Emery Tak Ada Bedanya dengan Wenger', 'FOOTBALL', '#arsenal #premierleague #arsenewenger #emmanuelpetit #unaiemery', 'bola.net', 'Mantan pemain Arsenal, Emmanuel Petit begitu kecewa dengan sikap pemilik The Gunners yang gagal mendukung Unai Emery dengan maksimal. Dia merasa pergantian pelatih dari Arsene Wenger ke Emery tak ada gunanya.<br>Arsenal memang mulai berkembang sejak ditangani Emery dan sempat melaju tak terkalahkan awal musim ini. Meski demikian, dalam beberapa laga terakhir Arsenal tampak mulai kehabisan bensin, Emery kehabisan taktik.<br>Kondisi ini disinyalir terjadi lantaran Emery belum benar-benar mendapatkan pemain yang dia butuhkan. Saat ini Emery hanya bisa memainkan pemain seadanya, yang bahkan tidak sesuai dengan taktik dia.<br>Oleh sebab itu, Petit merasa masalah Emery saat ini sama saja dengan era Wenger. Baca komentar selengkapnya di bawah ini ya, Bolaneters', 'assets/img/news/unai-emery-psg-angers-ligue-1-14032018jpg_1h1cpwz08uygy16r4jbwc5vno3.jpg', 'Andra'),
(17, 'Piala Super Italia, Gelar Pertama Cristiano Ronaldo bersama Juventus', 'FOOTBALL', '#juventus', 'bola.kompas.net', 'Mantan pemain Arsenal, Emmanuel Petit begitu kecewa dengan sikap pemilik The Gunners yang gagal mendukung Unai Emery dengan maksimal. Dia merasa pergantian pelatih dari Arsene Wenger ke Emery tak ada gunanya.<br>Arsenal memang mulai berkembang sejak ditangani Emery dan sempat melaju tak terkalahkan awal musim ini. Meski demikian, dalam beberapa laga terakhir Arsenal tampak mulai kehabisan bensin, Emery kehabisan taktik.<br>Kondisi ini disinyalir terjadi lantaran Emery belum benar-benar mendapatkan pemain yang dia butuhkan. Saat ini Emery hanya bisa memainkan pemain seadanya, yang bahkan tidak sesuai dengan taktik dia.<br>Oleh sebab itu, Petit merasa masalah Emery saat ini sama saja dengan era Wenger. Baca komentar selengkapnya di bawah ini ya, Bolaneters', 'assets/img/news/3485331194.jpg', 'Andra'),
(18, 'Jadwal Piala FA Putaran Keempat, Ada Big Match Arsenal Vs Manchester United', 'FOOTBALL', '#arsenal #facup #manchesterunited #bigmatch', 'tribunnews.com', 'Mantan pemain Arsenal, Emmanuel Petit begitu kecewa dengan sikap pemilik The Gunners yang gagal mendukung Unai Emery dengan maksimal. Dia merasa pergantian pelatih dari Arsene Wenger ke Emery tak ada gunanya.<br>Arsenal memang mulai berkembang sejak ditangani Emery dan sempat melaju tak terkalahkan awal musim ini. Meski demikian, dalam beberapa laga terakhir Arsenal tampak mulai kehabisan bensin, Emery kehabisan taktik.<br>Kondisi ini disinyalir terjadi lantaran Emery belum benar-benar mendapatkan pemain yang dia butuhkan. Saat ini Emery hanya bisa memainkan pemain seadanya, yang bahkan tidak sesuai dengan taktik dia.<br>Oleh sebab itu, Petit merasa masalah Emery saat ini sama saja dengan era Wenger. Baca komentar selengkapnya di bawah ini ya, Bolaneters', 'assets/img/news/arsenal-alexandre-lacazette-vs-tottenham-hotspur-3.jpg', 'Andra'),
(19, 'Paris Saint-Germain Siap Melepas Adrien Rabiot', 'FOOTBALL', '#psg #adrienrabbiot #transfer', 'tribunnews.com', 'Mantan pemain Arsenal, Emmanuel Petit begitu kecewa dengan sikap pemilik The Gunners yang gagal mendukung Unai Emery dengan maksimal. Dia merasa pergantian pelatih dari Arsene Wenger ke Emery tak ada gunanya.<br>Arsenal memang mulai berkembang sejak ditangani Emery dan sempat melaju tak terkalahkan awal musim ini. Meski demikian, dalam beberapa laga terakhir Arsenal tampak mulai kehabisan bensin, Emery kehabisan taktik.<br>Kondisi ini disinyalir terjadi lantaran Emery belum benar-benar mendapatkan pemain yang dia butuhkan. Saat ini Emery hanya bisa memainkan pemain seadanya, yang bahkan tidak sesuai dengan taktik dia.<br>Oleh sebab itu, Petit merasa masalah Emery saat ini sama saja dengan era Wenger. Baca komentar selengkapnya di bawah ini ya, Bolaneters', 'assets/img/news/adrien-rabiot-bungkukkloeeee_20160107_214547.jpg', 'Andra'),
(20, 'Gelandang Liverpool, Jordan Henderson Bandingkan Mohamed Salah Dengan Luis Suarez', 'FOOTBALL', '#liverpool #mohammadsalah', 'bola.net', 'Mantan pemain Arsenal, Emmanuel Petit begitu kecewa dengan sikap pemilik The Gunners yang gagal mendukung Unai Emery dengan maksimal. Dia merasa pergantian pelatih dari Arsene Wenger ke Emery tak ada gunanya.<br>Arsenal memang mulai berkembang sejak ditangani Emery dan sempat melaju tak terkalahkan awal musim ini. Meski demikian, dalam beberapa laga terakhir Arsenal tampak mulai kehabisan bensin, Emery kehabisan taktik.<br>Kondisi ini disinyalir terjadi lantaran Emery belum benar-benar mendapatkan pemain yang dia butuhkan. Saat ini Emery hanya bisa memainkan pemain seadanya, yang bahkan tidak sesuai dengan taktik dia.<br>Oleh sebab itu, Petit merasa masalah Emery saat ini sama saja dengan era Wenger. Baca komentar selengkapnya di bawah ini ya, Bolaneters', 'assets/img/news/liverpool-mohamed-salah-vs-west-ham-united-3_20180813_052551.jpg', 'Andra');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(225) NOT NULL,
  `status` varchar(10) NOT NULL,
  `foto` varchar(225) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `status`, `foto`) VALUES
(2, 'Andra', 'andradeva@gmail.com', '$2y$10$ED0jUETq0y.7wChSVjoA3ubM0m5AVhqDZiHPRh1MAsFr/lI4.T6XW', 'ADMIN', 'assets/img/upload/baru_1547388637.jpg'),
(3, 'Andra', 'andradevas@gmail.com', '$2y$10$ED0jUETq0y.7wChSVjoA3ubM0m5AVhqDZiHPRh1MAsFr/lI4.T6XW', 'USER', 'assets/img/user.png'),
(4, 'Rizuki', 'rizkikhair@gmal.com', '$2y$10$WkiQjcgZ1BJJIaDbGhwDGusXW69vhfbyR9ucGeM4XUhc6aLEYQdS.', 'USER', 'assets/img/user.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
